version: '3.3'
services:
  db:
    env_file:
      - secrets.env
      - generated.env
    build:
      context: ./db
    image: itcw/props_db:${APP_VERSION:-latest}
    restart: always
    ports:
    - 5432:5432
    volumes:
    - database_data:/var/lib/postgresql/data
  bot:
    env_file:
      - secrets.env
      - generated.env
    build:
      context: ./bot
    image: itcw/props_bot:${APP_VERSION:-latest}
    expose:
    - 8080
    ports:
    - 8080:8080
    links:
    - db
volumes:
  database_data:
    driver: local
